import type { ElfAnalysis, ReportV1 } from "../types";

export const fixtureAnalysis: ElfAnalysis = {
  metrics: {
    asset_bytes: 12_230_000,
    load_file_bytes: 10_400_000,
    load_memory_bytes: 10_470_000,
    executable_bytes: 10_260_000,
    read_only_bytes: 140_000,
    writable_bytes: 70_000,
    bss_zero_fill_bytes: 70_000,
    program_header_count: 2,
    section_count: 10,
    symbol_count: 7_126,
    stripped: false,
    has_debug_sections: false,
  },
  header: {
    class: "ELF64",
    little_endian: true,
    elf_type: "EXEC",
    machine: "RISC-V",
    entry: 0x80000000,
    entry_hex: "0x80000000",
    flags: 0,
    riscv_arch: "rv64im_zicsr",
    header_size: 64,
    program_header_offset: 64,
    program_header_entry_size: 56,
    section_header_offset: 12_229_232,
    section_header_entry_size: 64,
  },
  program_headers: [
    {
      kind: "PT_LOAD",
      offset: 0,
      virtual_address: 0x80000000,
      physical_address: 0x80000000,
      file_size: 10_260_000,
      memory_size: 10_260_000,
      flags: "RX",
      alignment: 4096,
    },
    {
      kind: "PT_LOAD",
      offset: 10_260_000,
      virtual_address: 0x809c9000,
      physical_address: 0x809c9000,
      file_size: 140_000,
      memory_size: 210_000,
      flags: "RW",
      alignment: 4096,
    },
  ],
  section_headers: [
    {
      name: "",
      kind: "SHT_NULL",
      flags: "",
      address: 0,
      offset: 0,
      size: 0,
      alignment: 0,
      entry_size: 0,
    },
    {
      name: ".text",
      kind: "SHT_PROGBITS",
      flags: "AX",
      address: 0x200800,
      offset: 0x800,
      size: 0x2cc7f8,
      alignment: 4,
      entry_size: 0,
    },
    {
      name: ".rodata",
      kind: "SHT_PROGBITS",
      flags: "AMS",
      address: 0x4ce000,
      offset: 0x2cd000,
      size: 0x1a380,
      alignment: 32,
      entry_size: 0,
    },
    {
      name: ".data",
      kind: "SHT_PROGBITS",
      flags: "WA",
      address: 0x4e9380,
      offset: 0x2e7380,
      size: 0x188,
      alignment: 8,
      entry_size: 0,
    },
    {
      name: ".bss",
      kind: "SHT_NOBITS",
      flags: "WA",
      address: 0x4e9508,
      offset: 0x2e7508,
      size: 0x208,
      alignment: 8,
      entry_size: 0,
    },
    {
      name: ".comment",
      kind: "SHT_PROGBITS",
      flags: "MS",
      address: 0,
      offset: 0x2e7508,
      size: 0xe7,
      alignment: 1,
      entry_size: 1,
    },
    {
      name: ".riscv.attributes",
      kind: "SHT_RISCV_ATTRIBUTES",
      flags: "",
      address: 0,
      offset: 0x2e75ef,
      size: 0x2a,
      alignment: 1,
      entry_size: 0,
    },
    {
      name: ".symtab",
      kind: "SHT_SYMTAB",
      flags: "",
      address: 0,
      offset: 0x2e761c,
      size: 0x1bd60,
      alignment: 4,
      entry_size: 16,
    },
    {
      name: ".shstrtab",
      kind: "SHT_STRTAB",
      flags: "",
      address: 0,
      offset: 0x30337c,
      size: 0x4f,
      alignment: 1,
      entry_size: 0,
    },
    {
      name: ".strtab",
      kind: "SHT_STRTAB",
      flags: "",
      address: 0,
      offset: 0x3033cb,
      size: 0x4e75c,
      alignment: 1,
      entry_size: 0,
    },
  ],
  symbols: {
    start: 0x80000000,
    main: 0x8005c734,
    heap_start: null,
    heap_end: null,
    read_input: true,
    write_output: true,
  },
  instructions: {
    source: "executable_sections",
    confidence: "high",
    decoded_instructions: 100,
    decoded_bytes: 400,
    undecodable_bytes: 0,
    compressed: 0,
    atomic: 0,
    floating_point: 0,
    privileged_or_syscall: 0,
    top_mnemonics: [],
  },
  accelerators: {
    standard_symbols: [],
    platform_symbols: [],
    note: "Static linked-symbol evidence only.",
  },
  checks: {},
};

const finding = {
  rule_id: "elf.header.class64",
  title: "ELF64 class",
  subject: "artifact" as const,
  status: "fail" as const,
  method: "static" as const,
  confidence: "high" as const,
  explanation: "The artifact is not ELF64.",
  standard_path: "standards/elf-loading-and-validation/README.md",
  standard_anchor: "header-validation",
  source_url: "https://github.com/eth-act/zkevm-standards",
  evidence: { elf64: false },
};

export const fixtureReport: ReportV1 = {
  schema_version: "1",
  generated_at: "2026-08-01T12:00:00Z",
  analyzer: { version: "0.1.0", commit: null },
  standards: {
    repository: "eth-act/zkevm-standards",
    requested_ref: "main",
    commit: "b1c0260785ca7dc5b44b1b58ab19d7dbe3ce6c05",
    tree: "tree",
    reviewed_snapshot: "b1c0260785ca7dc5b44b1b58ab19d7dbe3ce6c05",
    blobs: {},
    stale_paths: [],
  },
  release: {
    repository: "eth-act/ere-guests",
    tag: "v0.14.1",
    commit: "229ffa89a34a6b638f394985160f769681b9a5a9",
    published_at: "2026-07-31T08:54:01Z",
    url: "https://github.com/eth-act/ere-guests/releases/tag/v0.14.1",
    name: "v0.14.1",
    compiler: "0.14.0",
    workflow_url: null,
  },
  summary: { pass: 3, fail: 1, warning: 0, unknown: 2, not_applicable: 0 },
  artifacts: [
    {
      id: "stateless-validator-reth-openvm-v2.0.0",
      family_id: "stateless-validator-reth-openvm-v2.0.0",
      guest: "reth",
      guest_version: "c5dff62",
      zkvm: "openvm",
      zkvm_version: "v2.0.0",
      variant: "primary",
      origin: "compiled",
      release_target_label: "riscv32im",
      analysis: null,
      provenance: {
        elf: {
          name: "guest.elf",
          url: "https://github.com/guest.elf",
          size: 100,
          github_digest: null,
          computed_sha256: "abc",
          digest_matches: null,
          signature_url: null,
          signature_published: true,
          error: null,
        },
        verification_key: null,
        public_key_url: null,
        signature_policy: "presence_only",
        source: null,
        workflow_url: null,
        licenses: {
          repository: "eth-act/ere-guests",
          reference: "abc",
          mit: true,
          apache_2: true,
          inspected_paths: ["LICENSE-MIT", "LICENSE-APACHE"],
          error: null,
        },
      },
      findings: [finding],
      ingestion_warnings: [],
      operational_error: null,
    },
  ],
  platforms: [{ zkvm: "openvm", findings: [] }],
  readiness: [],
};
