import type { ReportV1 } from "../types";

const finding = {
  rule_id: "elf.header.class64",
  title: "ELF64 class",
  subject: "artifact" as const,
  status: "fail" as const,
  method: "static" as const,
  confidence: "high" as const,
  explanation: "The artifact is not ELF64.",
  standard_path: "standards/elf-loading-and-validation/README.md",
  standard_anchor: "header-validation",
  source_url: "https://github.com/eth-act/zkevm-standards",
  evidence: { elf64: false },
};

export const fixtureReport: ReportV1 = {
  schema_version: "1",
  generated_at: "2026-08-01T12:00:00Z",
  analyzer: { version: "0.1.0", commit: null },
  standards: {
    repository: "eth-act/zkevm-standards",
    requested_ref: "main",
    commit: "b1c0260785ca7dc5b44b1b58ab19d7dbe3ce6c05",
    tree: "tree",
    reviewed_snapshot: "b1c0260785ca7dc5b44b1b58ab19d7dbe3ce6c05",
    blobs: {},
    stale_paths: [],
  },
  release: {
    repository: "eth-act/ere-guests",
    tag: "v0.14.1",
    commit: "229ffa89a34a6b638f394985160f769681b9a5a9",
    published_at: "2026-07-31T08:54:01Z",
    url: "https://github.com/eth-act/ere-guests/releases/tag/v0.14.1",
    name: "v0.14.1",
    compiler: "0.14.0",
    workflow_url: null,
  },
  summary: { pass: 3, fail: 1, warning: 0, unknown: 2, not_applicable: 0 },
  artifacts: [
    {
      id: "stateless-validator-reth-openvm-v2.0.0",
      family_id: "stateless-validator-reth-openvm-v2.0.0",
      guest: "reth",
      guest_version: "c5dff62",
      zkvm: "openvm",
      zkvm_version: "v2.0.0",
      variant: "primary",
      origin: "compiled",
      release_target_label: "riscv32im",
      analysis: null,
      provenance: {
        elf: {
          name: "guest.elf",
          url: "https://github.com/guest.elf",
          size: 100,
          github_digest: null,
          computed_sha256: "abc",
          digest_matches: null,
          signature_url: null,
          signature_published: true,
          error: null,
        },
        verification_key: null,
        public_key_url: null,
        signature_policy: "presence_only",
        source: null,
        workflow_url: null,
        licenses: {
          repository: "eth-act/ere-guests",
          reference: "abc",
          mit: true,
          apache_2: true,
          inspected_paths: ["LICENSE-MIT", "LICENSE-APACHE"],
          error: null,
        },
      },
      findings: [finding],
      ingestion_warnings: [],
      operational_error: null,
    },
  ],
  platforms: [{ zkvm: "openvm", findings: [] }],
  readiness: [],
};
